[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = let g:jedi#use_tabs_not_buffers = 1
hook_add = let g:jedi#popup_select_first = 0
hook_add = let g:jedi#popup_on_dot = 0 
hook_add = let g:jedi#goto_command = "<leader>d"
hook_add = let g:jedi#goto_assignments_command = "<leader>g"
hook_add =  let g:jedi#goto_definitions_command = ""
hook_add =  let g:jedi#documentation_command = "K"
hook_add =  let g:jedi#usages_command = "<leader>n"
hook_add =  let g:jedi#rename_command = "<leader>R" #quick-runと競合しないように大文字Rに変更. READMEだと<leader>r
hook_add = autocmd FileType python setlocal completeopt-=preview #ポップアップを表示しない
