
# tap repositories and their packages

tap homebrew/core
brew anyenv
brew aria2
brew coreutils
brew docker
brew fzf
brew gcc
brew ghq
brew git
brew go
brew jq
brew mas
brew neovim
brew openssh
brew readline
brew tree
brew xz
brew zsh
brew zsh-completions

tap homebrew/cask-fonts

tap homebrew/cask-versions

tap homebrew/cask
cask balenaetcher
cask docker
cask iterm2
cask spectacle

tap beeftornado/rmtree
brew brew-rmtree
cask google-japanese-ime

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask daisydisk
cask google-chrome
cask iterm2
cask visual-studio-code

# App Store applications
appstore 1333542190 1Password 7 (7.4.1)
appstore 409183694 Keynote (9.2.1)
appstore 405399194 Kindle (1.26.1)
appstore 409203825 Numbers (6.2.1)
appstore 409201541 Pages (8.2.1)
appstore 1429033973 RunCat (6.4)
appstore 803453959 Slack (4.1.2)
appstore 1176895641 Spark (2.5.8)
appstore 1085114709 Parallels Desktop (1.5.0)
